### ISSUE TITLE
Relative URLs Please

### ISSUE THREAD

**Issue by angelcoding** [noumo/easyii#19]
This is looking like the start of a great project but please, please, please use relative urls in all HTML output.

Not everyone will be running this on the root of a domain so hard coded links to '/admin/....' with the leading slash won't always work.

You should really use the URL helper as much as possible - http://www.yiiframework.com/doc-2.0/guide-helper-url.html#creating-urls

**Comment by noumo** [comment]
Ofcourse you are right.
Hope will fix it with publishing subcategories feature.

**Comment by claudioferrari** [comment]
@angelcoding: any suggestions?
Did you found the parts to modify?

**Comment by angelcoding** [comment]
@claudioferrari There's loads e.g. `<a href="/admin/admins/edit/")...`. Use your IDE to search for anything with `/admin` in it, mostly in the views folder. Ideally these links should use the Url helper as mentioned above.
I have no time to do a PR myself and was just testing the code out so I haven't got any further than discovering there is a problem.

**Comment by claudioferrari** [comment]
...yeah, saw them; I am working with multilingual and multi theme issue; could you be so kind to handle urls?

**Comment by angelcoding** [comment]
@claudioferrari Are you asking me? If so, I'm not going to write code for you. This isn't even my project. Try the Yii2 forum if you need help - http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/

**Comment by Viniter** [comment]
Ok, I'm working on this issue right now. I'll submit a pull request once it's all done. There's quite a number of links and redirects and all of them use direct url linking instead of yii's Url Helper. 

I just want to ask you to use the helper from this point on, in lot of cases it only means putting your relative url in an array like `->redirect(['/admin/admins/'])` instead of `->redirect('/admin/admins/')`. Most of yii methods already use the Url Helper when you feed in an array.

**Comment by noumo** [comment]
Good news, thanks for help!

**Comment by noumo** [comment]
solved
