### ISSUE TITLE
error when installing 

### ISSUE THREAD

**Issue by ajkosh** [noumo/easyii#21]
i m getting this error
Fatal error: require(): Failed opening required 'C:/wamp/www//vendor/noumo/easyii/config/easyii.php' (include_path='.;C:\php\pear') in C:\wamp\www\temp\app\config\web.php on line 69

**Comment by noumo** [comment]
You should cut all files from "temp" folder to your web root folder.

**Comment by Viniter** [comment]
So far it seems Easyii is designed to work solely in Document Root. You can fix the config line manually to run the installation, but the rest of the project is coded with absolute URLs, so it's pointless to install anywhere but in root directory.

I would say this should be fixed along with issue #19, because forcing user to use root is not a great solution.

**Comment by noumo** [comment]
Im absolutely agree and need some time so solve and test this issue after incoming new core features.

**Comment by Viniter** [comment]
This particular issue is part of the `easyii-start` code. I made an issue in the correct repository:
noumo/easyii-start#2

This issue can be closed.

**Comment by antonior14** [comment]
Hi! I'm getting blank page when I try to install easyii-shop
I folowed installation steps at http://easyiicms.com/docs/install
why??

**Comment by noumo** [comment]
Check your php version, it must be 5.4+
